// File: m_delay_line_w10.v
// Generated by MyHDL 0.9dev
// Date: Mon Jul 21 18:53:12 2014


`timescale 1ns/10ps

module m_delay_line_w10 (
    clk,
    delay,
    din,
    dout
);


input clk;
input [3:0] delay;
input [9:0] din;
output [9:0] dout;
wire [9:0] dout;


reg [9:0] dline [0:16-1];




always @(posedge clk) begin: M_DELAY_LINE_W10_RTL
    integer ii;
    dline[0] <= din;
    for (ii=1; ii<16; ii=ii+1) begin
        dline[ii] <= dline[(ii - 1)];
    end
end



assign dout = dline[delay];

endmodule
