language: python
python:
  - "2.7"
  - "pypy"

# get some stuff to install
before_install:
  - sudo apt-get install iverilog

# command to install dependencies
install:
  - pwd
  - chmod +x ./scripts/ci/install_myhdl.sh
  - pip install git+https://github.com/cfelton/minnesota
  - pip install coverage
  - pip install coveralls

# run the test, nosetests can be used
script:
  - cd test
  - python test_jpegenc.py

notifications:
  email: false
